apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: metacoding
spec:
  type: ClusterIP  # 내부 통신만 허용(기본값)
  selector:
    app: order
  ports:
    - port: 8081
      targetPort: 8081