apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-configmap
  namespace: metacoding
data:
  DB_URL: jdbc:mysql://metacofing-msa.cfcouus4ix90.ap-northeast-2.rds.amazonaws.com:3306/metacoding_msa?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
  DB_DRIVER: com.mysql.cj.jdbc.Driver
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092