apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: metacoding
spec:
  type: ClusterIP  # 내부 통신만 허용(기본값)
  selector:
    app: delivery
  ports:
    - port: 8084
      targetPort: 8084