apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: metacoding
spec:
  type: ClusterIP  # 내부 통신만 허용(기본값)
  selector:
    app: product
  ports:
    - port: 8082
      targetPort: 8082