apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: metacoding
type: Opaque
stringData:
  JWT_SECRET: mySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLongForHS256Algorithm
  JWT_EXPIRATION: "86400000"










